[package]
name = "avery"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.3"
hepmc2 = { version = "0.5.1", optional = true }
itertools = "0.11.0"
lhef = { version = "0.5.0", optional = true }
ntuple = { version = "0.7.0", optional = true }
particle_id = "0.3.0"
petgraph = "0.6.3"

[features]
default = ["lhef", "hepmc2"]
